name: spell-check
description: Run spell check over your files in docker image
author: https://github.com/nsuma8989
requirements:
  - docker
configuration:
  properties:
    files:
      type: [string, array]
      minItems: 1
  required:
    - files
