name: spell-check
description: Run spell check over your files in docker image
author: https://github.com/nsuma8989
requirements: []
configuration:
  properties:
    files:
      type: string
  required:
    - files
