#!/bin/bash
set -euo pipefail
echo "Running spell check on files"
if docker run --rm -v "$PWD:/workdir" "tmaier/markdown-spellcheck:latest" --report "${files[@]}" ; then
  echo "Spelling errors in the file ${#files[@]}"
else
  exit 1
fi
