#!/bin/bash
set -euo pipefail



echo "Running spell check on ${#files[@]} files"
if docker run --rm -v "$PWD:/mnt" --workdir "/mnt" "starefossen/aspell:latest" "${files[@]}" ; then
  echo "No spelling errors in the files"
else
  exit 1
fi
