#!/bin/bash
set -euo pipefail
echo "Running spell check on file"
if docker run --rm -v "$PWD:/workdir" "tmaier/markdown-spellcheck:latest" --report "${file}" ; then
  echo "Spelling errors in the file"
else
  exit 1
fi
